service:
  name: serverless-morphological-analysis
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1

functions:
  text-analysis:
    handler: lambda/index.handler
    memorySize: 128
    timeout: 900
    events:
      - http:
          method: get
          path: morphologic/parse
  event-sample:
    handler: lambda/event.handler
    memorySize: 128
    timeout: 900
    events:
      - schedule:
          rate: rate(2 minutes)
          enabled: true
          input:
            key1: value1
            key2: value2
            stageParams:
              stage: dev