swagger: "2.0"
info:
  description: "これは形態素解析をAWS Lambdaで行ってくれるAPIです"
  version: "1.0.0"
  title: "TextAnalizeAPI"
  contact:
    email: "keep_slimbody@yahoo.co.jp"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  host: "https://y8lqfim18c.execute-api.ap-northeast-1.amazonaws.com"
  basePath: "/dev"
paths:
  /morphologic/parse:
    get:
      summary: "execute morphologic analysis"
      description: ""
      parameters:
      - name: "sentence"
        in: "query"
        description: "original sentence"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "doggie"